# Generated by Django 5.2.1 on 2025-05-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
