# Generated by Django 5.1.3 on 2025-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio_Core", "0002_contact_created_at_contact_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
