# Generated by Django 5.1.3 on 2025-08-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio_Core", "0003_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.CharField(max_length=100)),
                ("end_date", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")],
                        default="left",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="Portfolio_Core.journeycard",
                    ),
                ),
            ],
        ),
    ]
